version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  groups:
    python-packages:
      patterns:
        - "*"
  open-pull-requests-limit: 2
  allow:
    - dependency-type: direct
    - dependency-type: indirect