from pathlib import Path

from pymatgen.core.lattice import Lattice
from pymatgen.core.structure import Structure

from doped.generation import DefectsGenerator
from doped.gpaw import GPAWDefectRelaxSet


def write_competing_phase_inputs(gpaw_settings):
    """Write GPAW single-point inputs for the Mg/O elemental references."""
    script_dir = Path(__file__).resolve().parent
    competing_phases_dir = script_dir.parent / "MgO" / "CompetingPhases"
    output_dir = Path("CompetingPhases_GPAW")

    # These structures were generated by the doped CompetingPhases workflow.
    phase_names = (
        "Mg_Fm-3m_EaH_0",
        "Mg_P6_3mmc_EaH_0.009",
        "Mg_R-3m_EaH_0.003",
        "O2_mmm_EaH_0",
    )
    for phase_name in phase_names:
        structure_path = competing_phases_dir / phase_name / "vasp_std" / "POSCAR"
        if not structure_path.exists():
            raise FileNotFoundError(
                f"Missing CompetingPhases structure: {structure_path}. "
                "Run this script from a full doped source checkout."
            )

        phase_structure = Structure.from_file(structure_path)
        phase_settings = {
            **gpaw_settings,
            "kpts": {"density": 3.0, "gamma": True},
            "occupations": {"name": "fermi-dirac", "width": 0.1},
        }
        if phase_name.startswith("O2_"):
            # Isolated triplet O2: Gamma-only sampling and one initial moment
            # on each oxygen atom.
            phase_settings.update(
                {
                    "kpts": {"size": (1, 1, 1), "gamma": True},
                    "occupations": {"name": "fermi-dirac", "width": 0.01},
                    "initial_magnetic_moments": [1.0, 1.0],
                }
            )

        print(f"Setting up competing phase {phase_name}...")
        phase_set = GPAWDefectRelaxSet(
            phase_structure,
            charge_state=0,
            gpaw_settings=phase_settings,
            calculation_type="singlepoint",
        )
        phase_set.write_input(output_dir / phase_name)


def main():
    print("Generating MgO bulk structure natively...")
    # Native structure generation
    lattice = Lattice.cubic(4.21)
    bulk_structure = Structure.from_spacegroup(
        "Fm-3m",
        lattice,
        ["Mg", "O"],
        [[0, 0, 0], [0.5, 0.5, 0.5]],
    )

    print("Generating MgO defects (forcing Mg_O antisites)...")
    # Force the generation of the Mg_O antisite using the extrinsic flag
    defect_gen = DefectsGenerator(bulk_structure, extrinsic={"O": "Mg"})

    # GPAW Parameters
    gpaw_settings = {
        "mode": {"name": "pw", "ecut": 250},
        "kpts": {"size": (1, 1, 1), "gamma": True},
        "xc": "PBE",
    }

    print("Writing GPAW input files...")

    # Setup Bulk using the finalized API parameters
    bulk_set = GPAWDefectRelaxSet(
        defect_gen.bulk_supercell,
        charge_state=0,
        gpaw_settings=gpaw_settings,
    )
    bulk_set.write_input("bulk")

    # Setup Defects
    for defect_name, defect_entry in defect_gen.defect_entries.items():
        # Example of filtering defects:
        # if "v_Mg" not in defect_name and "Mg_O" not in defect_name:
        #     continue

        print(f"Setting up {defect_name}...")

        # Pass the entry directly, and use the gpaw_settings dictionary
        defect_set = GPAWDefectRelaxSet(
            defect_entry,
            charge_state=defect_entry.charge_state,
            gpaw_settings=gpaw_settings,
        )
        defect_set.write_input(defect_name)

        # Create a true static single-point example for the Mg_O +1 state
        if "Mg_O" in defect_name and defect_entry.charge_state == 1:
            unrelaxed_name = defect_name + "_unrelaxed"
            print(f"Setting up {unrelaxed_name}...")

            singlepoint_set = GPAWDefectRelaxSet(
                defect_entry,
                charge_state=defect_entry.charge_state,
                gpaw_settings=gpaw_settings,
                calculation_type="singlepoint",
            )
            singlepoint_set.write_input(unrelaxed_name)

    print("Writing GPAW inputs for the Mg/O competing phases...")
    write_competing_phase_inputs(gpaw_settings)

    print("Workflow setup complete! You can now run the calculations.")


if __name__ == "__main__":
    main()
