"""
Pure numerical global-search engine, used by
:meth:`~doped.thermodynamics.FermiSolver.optimise`.

Implements a robust global optimisation strategy over convex polytopes
(chemical potential stability regions): a dense physics-scaled first pass,
a beam of spatially separated candidate optima with an independent 'zoom'
branch for each (i.e. beam search `after` dense initial scan, to avoid missing
narrow minima), a final local polish per converged branch, and a random
post-convergence audit over the full polytope with automatic re-seeding.
Overkill in most cases, but far more robust and reliable in identifying unusual
extrema in chemical potential space. See the
:meth:`~doped.thermodynamics.FermiSolver.optimise` docstring for the full
algorithm description and physical reasoning.

This module is deliberately independent of any DFT/defect specifics: the target
function is supplied as an ``evaluate`` callable, and search grids are
generated by a ``make_grid`` callable.

Conventions used throughout: points are rows of full chemical potential
coordinates (one column per element). Distances, hulls and triangulations use
only the μ columns that actually vary independently -- determined by matrix
rank -- dropping dependent or (near-)constant (e.g. ``fixed_elements``)
dimensions. ``evaluate`` follows a higher-is-better convention (negate the
target for minimisation).
"""

import itertools
import warnings
from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from scipy.constants import value as constants_value
from scipy.optimize import minimize
from scipy.spatial import Delaunay, QhullError, cKDTree

_kB = constants_value("Boltzmann constant in eV/K")  # ~8.617e-5 eV/K


def _landscape_smoothness_scale(
    temperature: float = 300,
    annealing_temperature: float | None = None,
    quenched_temperature: float = 300,
    free_defects: list[str] | None = None,
) -> float:
    """
    Characteristic smoothness scale (in eV of chemical potential) of the
    defect/carrier concentration landscape, for choosing the default first-pass
    grid resolution in ``FermiSolver.optimise``.

    The smoothing scale of the landscape is set by the lowest temperature at
    which any `μ-coupled/dependent` degree of freedom still responds
    (significantly): kT for full thermodynamic equilibrium, kT_anneal for
    frozen-defect anneal+quench protocols (total defect concentrations set at
    the annealing temperature), and kT_quench once species re-equilibrate
    against the reservoir at the quenched temperature (``free_defects``).
    Any future/unrecognised quenching protocol should use
    ``kB * min(all temperatures in the protocol)`` as a conservative
    fallback (the pattern followed here).

    Charge state re-population upon quenching (with total defect concentrations
    fixed) does not sharpen `total` concentration landscapes below kT_anneal
    (μ enters the quenched solve only via the frozen totals), but
    charge-state-resolved targets (e.g. ``"v_O_+1"``) can peak sharply where
    the quenched Fermi level transits a transition level at the quench
    compensation crossover -- where the sub-kT_anneal first-pass refinement of
    ``_default_grid_resolution`` improves coverage.

    Note that this is a `heuristic` for choosing the default grid density, not
    a complete measure of the roughness of the optimisation surface.
    The extreme case is where the net fixed defect/dopant charge ``Q_def(μ)``
    changes sign along the scan (a compensation crossover) with no buffering
    defect level inside the ``E_F`` window swept at the crossing. ``E_F`` is
    then pinned by carriers alone and ``d(ln p)/dμ`` grows as ``1/|μ - μ*|``
    near the crossover μ* (divergent). This is fine for the solve algorithm due
    to the random post-convergence audit (which samples the full polytope,
    independent of grid spacing) and the per-branch local polish of
    ``FermiSolver.optimise``, while the returned kT scale needs only to resolve
    the smooth background landscape (and can be overridden via the
    ``initial_grid_resolution`` argument).

    Args:
        temperature (float):
            Temperature (K) for full-equilibrium solves (used when
            ``annealing_temperature`` is ``None``). Default is 300 K.
        annealing_temperature (float | None):
            Annealing temperature (K) for the frozen defect approach, if used.
            Default is ``None``.
        quenched_temperature (float):
            Quenched temperature (K) for the frozen defect approach.
            Default is 300 K.
        free_defects (list[str] | None):
            Defects excluded from high-temperature concentration fixing
            (see ``FermiSolver.optimise``). Default is ``None``.

    Returns:
        float:
            The landscape smoothness scale in eV.
    """
    if annealing_temperature is None:
        return _kB * temperature  # full equilibrium; target log-slopes scale as 1/kT

    if free_defects:  # re-equilibrate against the reservoir at T_quench; respond down to kT_quench
        return _kB * min(annealing_temperature, quenched_temperature)

    return _kB * annealing_temperature  # frozen totals (± frozen charge states); c(μ) ~ exp(-ΔH/kT_anneal)


def _independent_columns(rows: np.ndarray, tol: float = 2e-3) -> np.ndarray:
    """
    Indices of a rank-revealing subset of affine-independent columns of
    ``rows`` (i.e. the independent chemical potential coordinates/dimensions of
    a set of chemical potential limits / grid points), greedily retaining each
    column which increases the affine rank -- so constant (e.g.
    ``fixed_elements``) and dependent columns are excluded.

    A column is dependent if it is linear in the retained columns to within a
    per-row RMS residual of ``tol`` times the largest column span, or 3 units
    of the decimal rounding of ``rows`` if larger: rows rounded to ``d``
    decimal places (e.g. 4 for ``CompetingPhasesAnalyzer`` chemical potential
    limits, 6 for ``ChemicalPotentialGrid`` grids) carry independent per-row
    residuals of up to ``0.5e-d`` in any linear (e.g. stoichiometric) relation
    between their columns.
    """
    rows = np.asarray(rows, dtype=float)
    max_span = float(np.ptp(rows, axis=0).max())
    if not max_span:  # all rows identical
        return np.array([], dtype=int)
    rounding = next(  # decimal rounding unit of the rows (0 if unrounded, e.g. contracted branch domains)
        (10.0**-d for d in range(2, 9) if np.allclose(rows, np.round(rows, d), atol=10.0 ** -(d + 3))), 0.0
    )
    rank_tol = max(tol, 3 * rounding / max_span)
    scaled = (rows - rows.mean(axis=0)) / (np.sqrt(len(rows)) * max_span)  # SVs: per-row RMS / max span
    independent: list[int] = []
    for j in range(rows.shape[1]):
        if np.linalg.matrix_rank(scaled[:, [*independent, j]], tol=rank_tol) > len(independent):
            independent.append(j)
    return np.array(independent, dtype=int)


def _default_grid_resolution(
    make_grid: Callable[..., np.ndarray],
    vertices: np.ndarray,
    *,
    smoothness_scale: float | None = None,
    temperature: float = 300,
    annealing_temperature: float | None = None,
    quenched_temperature: float = 300,
    free_defects: list[str] | None = None,
    max_initial_points: int = 100_000,
) -> float:
    """
    Resolve the default first-pass grid resolution for
    ``FermiSolver.optimise``.

    This is the landscape smoothness scale (``_landscape_smoothness_scale``),
    opportunistically refined toward the minimum-temperature floor
    (``kB * min(all temperatures)``) while the implied grid size stays within
    a soft budget of 25% of ``max_initial_points``. Below the
    minimum-temperature floor, no grid spacing resolves anything further
    (sub-kT_quench quasi-steps are the audit's responsibility, not the grid's).

    Deliberately independent of the search ``tolerance``: the initial
    resolution is a completeness knob (in eV of chemical potential) set by the
    landscape (with the goal of qualitatively identifying all possible/relevant
    basins), while ``tolerance`` is a termination/precision knob (controls
    search contraction `within basins`).

    Args:
        make_grid (Callable):
            Grid generator; see ``_beam_zoom_search``. Used to probe the grid
            size implied by candidate resolutions (so refinement is costed on
            the grids produced).
        vertices (np.ndarray):
            ``(V, k)`` array of polytope vertices; see ``_beam_zoom_search``.
        smoothness_scale (float | None):
            Pre-computed landscape smoothness scale (eV) to start refinement
            from, taking precedence over the protocol arguments below (which
            then only set the refinement floor). Default is ``None`` (compute
            via ``_landscape_smoothness_scale``).
        temperature (float):
            See ``_landscape_smoothness_scale``. Default is 300 K.
        annealing_temperature (float | None):
            See ``_landscape_smoothness_scale``. Default is ``None``.
        quenched_temperature (float):
            See ``_landscape_smoothness_scale``. Default is 300 K.
        free_defects (list[str] | None):
            See ``_landscape_smoothness_scale``. Default is ``None``.
        max_initial_points (int):
            Hard cap on the number of first-pass grid points (25% of which
            is the soft refinement budget). Default is 100,000.

    Returns:
        float:
            The resolved first-pass grid resolution in eV.
    """
    resolution = (
        smoothness_scale
        if smoothness_scale is not None
        else _landscape_smoothness_scale(
            temperature,
            annealing_temperature,
            quenched_temperature,
            free_defects,
        )
    )
    floor = _kB * (  # kB * min(all temperatures in the solve protocol):
        min(annealing_temperature, quenched_temperature)
        if annealing_temperature is not None
        else temperature
    )
    vertices = np.asarray(vertices, dtype=float)
    probe = make_grid(vertices, resolution=resolution)
    # infer the affine dimension from the grid actually built, ``fixed_elements`` columns are constant etc:
    n_free_dims = max(len(_independent_columns(probe)), 1)
    while resolution > floor and len(probe) < 0.25 * max_initial_points:  # soft budget of 25% of max
        if len(probe) * 2**n_free_dims > max_initial_points:
            break  # next refinement would exceed the hard cap
        resolution = max(floor, resolution / 2)
        probe = make_grid(vertices, resolution=resolution)
    return resolution


class _PolytopeInterp:
    """
    Piecewise-linear interpolation and uniform random sampling over the convex
    polytope spanned by a set of full-coordinate rows.

    Distances, hulls and triangulations use only the μ columns that actually
    vary independently (linearly dependent and near-constant columns are
    dropped); interpolation and sampling then act on the full rows, so
    dependent and fixed values come for free as barycentric combinations.
    """

    def __init__(self, rows: np.ndarray):
        rows = np.asarray(rows, dtype=float)
        self.rows = np.vstack([rows, rows.mean(axis=0)])  # append centroid; qhull Delaunay requires...
        candidates = _independent_columns(self.rows)  # ...more than a single simplex (> g+1 points)
        if not len(candidates):
            raise ValueError("The optimisation polytope has no varying dimensions.")

        self.varying = np.zeros(self.rows.shape[1], dtype=bool)  # geometry column mask (full width)
        self.varying[candidates] = True
        self.coords = self.rows[:, self.varying]
        if self.coords.shape[1] == 1:  # 1D line segment; scipy Delaunay requires >= 2D
            self.delaunay = None
            lo, hi = np.argmin(self.coords[:, 0]), np.argmax(self.coords[:, 0])
            self._lo, self._hi = self.rows[lo], self.rows[hi]
            self._x0, self._x1 = self.coords[lo, 0], self.coords[hi, 0]
        else:
            self.delaunay = Delaunay(self.coords, qhull_options="QJ Qbb Qc")
            simplex_edges = np.diff(self.coords[self.delaunay.simplices], axis=1)  # (S, g, g)
            self.volumes = np.abs(np.linalg.det(simplex_edges))  # ∝ simplex volumes (det/g! formula)

    def lift(self, X: np.ndarray) -> np.ndarray:
        """
        Return full coordinate rows for the given geometry (``varying`` column)
        coordinates ``X`` (shape ``(M, g)``), interpolating the dependent (and
        any fixed) columns; rows are NaN for points outside the polytope.
        """
        X = np.atleast_2d(X)
        out = np.full((len(X), self.rows.shape[1]), np.nan)
        if self.delaunay is None:  # 1D; simple interpolation
            w = (X[:, 0] - self._x0) / (self._x1 - self._x0)
            inside = (w >= -1e-9) & (w <= 1 + 1e-9)
            out[inside] = self._lo + np.clip(w[inside], 0, 1)[:, None] * (self._hi - self._lo)
            return out

        s = self.delaunay.find_simplex(X, tol=1e-9)
        inside = s >= 0
        if inside.any():
            T = self.delaunay.transform[s[inside]]  # (M, g+1, g); barycentric transform per simplex
            b = np.einsum("mij,mj->mi", T[:, :-1], X[inside] - T[:, -1])
            weights = np.concatenate([b, 1 - b.sum(axis=1, keepdims=True)], axis=1)  # (M, g+1)
            out[inside] = np.einsum("mi,mik->mk", weights, self.rows[self.delaunay.simplices[s[inside]]])
        return out

    def sample(self, n: int, rng: np.random.Generator) -> np.ndarray:
        """
        Draw ``n`` uniform random points (full coordinate rows) over the
        polytope: simplices chosen with probability ∝ volume, positions via
        flat Dirichlet barycentric weights.
        """
        if self.delaunay is None:  # 1D; simple random sample over interpolated line
            return self._lo + rng.uniform(size=(n, 1)) * (self._hi - self._lo)

        total_volume = self.volumes.sum()
        p = self.volumes / total_volume if total_volume > 0 else None  # None -> uniform over simplices
        s = rng.choice(len(self.volumes), size=n, p=p)  # uniform samples; weighted by simplex volumes
        weights = rng.dirichlet(np.ones(self.coords.shape[1] + 1), size=n)  # (n, g+1)
        return np.einsum("ni,nik->nk", weights, self.rows[self.delaunay.simplices[s]])


def _nearest_distances(points: np.ndarray) -> np.ndarray:
    """
    Distance from each point to its nearest `distinct` other point (``inf`` if
    there is none), where points within the 6-decimal-place solve-cache
    resolution (e.g. prepended exact vertices and their rounded lattice twins)
    count as the same point.

    Their median is a robust estimate of the achieved grid spacing, for any
    grid generation scheme.
    """
    points = np.asarray(points, dtype=float)
    unique_points = np.unique(np.round(points, 6), axis=0)
    if len(unique_points) < 2:
        return np.full(len(points), np.inf)
    return np.asarray(cKDTree(unique_points).query(points, k=2)[0])[:, 1]


def _adjacent_pairs(points: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Adjacency of a set of sample points: the edges of their Delaunay graph
    (consecutive points along the line, in 1D) -- so adjacency adapts to
    non-uniform sample spacing (e.g. hybrid grids). Duplicate points map to a
    single node.

    Returns:
        tuple[np.ndarray, np.ndarray]:
            ``nodes``: indices (into ``points``) of the unique representative
            points, and ``pairs``: ``(E, 2)`` array of adjacent index pairs
            (into ``points``).
    """
    unique_points, nodes = np.unique(np.round(points, 6), axis=0, return_index=True)
    n_nodes, ndim = unique_points.shape
    if ndim == 1:  # 1D: consecutive points along the line
        order = np.argsort(unique_points[:, 0])
        pairs = np.column_stack([order[:-1], order[1:]])
    elif n_nodes <= ndim + 1:  # too few points for triangulation; all mutually adjacent
        pairs = np.array(list(itertools.combinations(range(n_nodes), 2)), dtype=int).reshape(-1, 2)
    else:
        try:
            simplices = Delaunay(unique_points).simplices  # (S, ndim + 1)
        except QhullError:  # degenerate sample (e.g. near-flat); joggle the input ("QJ") -- only as a
            # fallback, as joggling collinear hull points can make the hull skip some, giving long sliver
            # edges between far-apart boundary points (spurious adjacency):
            simplices = Delaunay(unique_points, qhull_options="QJ").simplices
        pairs = np.vstack([simplices[:, [a, b]] for a, b in itertools.combinations(range(ndim + 1), 2)])
        pairs = np.unique(np.sort(pairs, axis=1), axis=0)
    return nodes, nodes[pairs]


def _select_seeds(
    points: np.ndarray, values: np.ndarray, spacing: float, max_beam_width: int, separation: float = 3.0
) -> list[int]:
    """
    Select up to ``max_beam_width`` beam-search seed indices from sampled
    ``(points, values)``.

    Seeds are the discrete local optima of the sample -- points whose value is
    >= that of every adjacent sample point (see ``_adjacent_pairs``) -- ranked
    by value and greedily deduplicated with a Chebyshev (∞-norm) separation of
    ``separation * spacing``.

    Fewer seeds than ``max_beam_width`` is normal (typically a single seed, as
    most chemical potential landscapes are unimodal).
    """
    nodes, pairs = _adjacent_pairs(points)
    neighbour_max = np.full(len(points), -np.inf)  # max value over each point's adjacent points
    np.maximum.at(neighbour_max, pairs[:, 0], values[pairs[:, 1]])
    np.maximum.at(neighbour_max, pairs[:, 1], values[pairs[:, 0]])
    candidates = nodes[values[nodes] >= neighbour_max[nodes]]  # discrete local maxima (deduplicated)
    candidates = sorted(  # failed solves (-inf) are never seeds:
        (i for i in candidates if np.isfinite(values[i])), key=lambda i: values[i], reverse=True
    )

    seeds: list[int] = []
    for i in candidates:
        if all(np.max(np.abs(points[i] - points[j])) >= separation * spacing for j in seeds):
            seeds.append(i)
            if len(seeds) == max_beam_width:
                break
    return seeds


@dataclass
class _SearchResult:
    """
    Result of a ``_beam_zoom_search``: the best point/value found (in the
    higher-is-better convention of ``evaluate``; the best over `all`
    evaluations, pooled over first pass, branches, polish and audit).
    """

    point: np.ndarray
    value: float


def _beam_zoom_search(
    evaluate: Callable[[np.ndarray], np.ndarray],
    vertices: np.ndarray,
    *,
    make_grid: Callable[..., np.ndarray],
    max_beam_width: int = 5,
    n_points: int = 30,
    initial_grid_resolution: float | None = None,
    tolerance: float = 0.01,
    n_audit_points: int = 200,
    polish: bool = True,
    max_iterations: int = 50,
    polytope_rows: np.ndarray | None = None,
    rng: int | np.random.Generator | None = None,
) -> _SearchResult:
    """
    Robust global maximisation of the ``evaluate`` function (callable) over the
    convex polytope spanned by ``vertices``, via dense first pass + beam search
    with per-branch domain contraction ("zooming") + local polish + random
    audit with re-seeding. See the
    :meth:`~doped.thermodynamics.FermiSolver.optimise` docstring for the full
    algorithm description.

    Args:
        evaluate (Callable):
            Maps an ``(M, k)`` array of points (full chemical potential
            coordinates) to an ``(M,)`` array of target values, with a
            higher-is-better convention (negate the target inside ``evaluate``
            for minimisation). Expected to cache repeated evaluations if they
            are expensive.
        vertices (np.ndarray):
            ``(V, k)`` array of polytope vertices (rows of full chemical
            potential coordinates).
        make_grid (Callable):
            ``make_grid(vertices, n_points=..., resolution=...)`` returns an
            ``(M, k)`` array of grid points spanning the polytope of the given
            vertices; ``resolution`` (eV) takes precedence over ``n_points``
            when not ``None``.
        max_beam_width (int):
            Maximum number of independent contraction branches (one per
            distinct discrete local optimum of the first-pass sample; see
            ``_select_seeds``). Default is 5.
        n_points (int):
            Grid size per branch per contraction iteration (the dense first
            pass instead uses ``initial_grid_resolution``, if set, otherwise
            also ``n_points``). Default is 30.
        initial_grid_resolution (float | None):
            Grid spacing (eV) for the dense first pass. ``None`` or ``inf``
            skips the dense pass, using an ``n_points`` first-pass grid instead
            (fast/legacy behaviour). Default is ``None``.
        tolerance (float):
            Relative convergence tolerance on the target value (per-branch
            stopping and audit acceptance). Default is 0.01.
        n_audit_points (int):
            Number of uniform random audit points over the full polytope after
            all branches converge; ``0`` disables. Default is 200.
        polish (bool):
            Whether to run a final Nelder-Mead local refinement from each
            converged branch optimum (recommended; the relative-change stopping
            rule alone typically leaves a few-percent value error). Default is
            ``True``.
        max_iterations (int):
            Maximum contraction iterations per branch. Default is 50.
        polytope_rows (np.ndarray | None):
            Rows spanning the true feasible polytope, if different from
            ``vertices`` (e.g. the constrained sub-polytope vertices with
            ``fixed_elements``); used for audit sampling and polish feasibility
            / interpolation. Default ``None`` (use ``vertices``).
        rng (int | np.random.Generator | None):
            Seed or generator for audit sampling. Default ``None`` (seed 0;
            deterministic).

    Returns:
        _SearchResult:
            The best point/value found.
    """
    vertices = np.asarray(vertices, dtype=float)
    rng = np.random.default_rng(0 if rng is None else rng)
    interp = _PolytopeInterp(polytope_rows if polytope_rows is not None else vertices)
    pooled_point: np.ndarray | None = None
    pooled_value = -np.inf

    def geom(points: np.ndarray) -> np.ndarray:  # geometry (varying independent) columns of points
        return points[:, interp.varying]

    def run(points: np.ndarray) -> np.ndarray:  # evaluate and track the best, guarding failed solves
        nonlocal pooled_point, pooled_value
        vals = np.asarray(evaluate(points), dtype=float)
        values = np.where(np.isfinite(vals), vals, -np.inf)
        if len(values):
            best_idx = int(np.argmax(values))
            if pooled_point is None or values[best_idx] > pooled_value:
                pooled_point, pooled_value = points[best_idx].copy(), float(values[best_idx])
        return values

    if initial_grid_resolution is not None and np.isfinite(initial_grid_resolution):
        first_resolution: float | None = float(initial_grid_resolution)
    else:  # fast/legacy behaviour: plain ``n_points`` first-pass grid
        first_resolution = None

    points = make_grid(vertices, resolution=first_resolution)  # dense first-pass
    values = run(points)
    geometry_points = geom(points)
    nearest = _nearest_distances(geometry_points)
    spacing = float(np.median(nearest))  # typical grid spacing

    def run_branch(seed_point: np.ndarray, seed_value: float, local_spacing: float) -> None:
        """
        Contract an independent domain around the seed until converged (see
        ``FermiSolver.optimise``), then optionally polish.
        """
        branch_vertices = vertices.copy()
        # localise the branch domain to the seed's neighbourhood first: a seed is a local optimum of the
        # sampled landscape, so its basin peak lies within ~1 grid spacing. Localise by halving around the
        # ``seed_point``, in a bounded loop (to avoid zero/degenerate spacing issues):
        for _ in range(100):
            if np.max(np.abs(geom(branch_vertices) - geom(seed_point[None]))) <= 3 * local_spacing:
                break  # localised
            branch_vertices = (branch_vertices + seed_point) / 2

        best_point, best_value = seed_point, seed_value
        previous_value, n_consecutive, converged = None, 0, False
        for _ in range(max_iterations):
            branch_vertices = (branch_vertices + best_point) / 2  # contract towards branch incumbent
            branch_points = make_grid(branch_vertices, n_points=n_points)
            branch_values = run(branch_points)
            best_idx = int(np.argmax(branch_values))
            if branch_values[best_idx] > best_value:
                best_point, best_value = branch_points[best_idx], float(branch_values[best_idx])

            if previous_value is not None and (
                best_value == previous_value
                or abs((best_value - previous_value) / (previous_value or best_value)) < tolerance
            ):  # relative-change criterion; require it on two consecutive iterations before stopping, ...
                n_consecutive += 1  # ...to avoid premature convergence on plateaus
                if n_consecutive >= 2:
                    converged = True
                    break
            else:
                n_consecutive = 0
            previous_value = best_value

            if np.max(np.abs(geom(branch_vertices) - geom(best_point[None]))) < 1e-3:
                converged = True  # branch domain contracted to < 1 meV diameter
                break

        if not converged:
            warnings.warn(
                f"An `optimise` search branch reached max_iterations ({max_iterations}) without meeting "
                f"the convergence criteria; results may be unconverged."
            )
        if polish:
            polish_branch(best_point, best_value)

    def polish_branch(best_point: np.ndarray, best_value: float) -> None:
        """
        Final local refinement (Nelder-Mead over the varying independent
        coordinates, with a hull-violation penalty), evaluating through
        ``evaluate`` (so results are pooled/cached like all others).
        """
        x0 = geom(best_point[None])[0]

        def objective(x: np.ndarray) -> float:
            lifted = interp.lift(x[None])
            if np.isnan(lifted).any():  # outside the feasible polytope; graded penalty to guide...
                return 1e100 * (1 + float(np.linalg.norm(x - x0)))  # ...Nelder-Mead back inside
            return -float(run(lifted)[0])

        minimize(
            objective,
            x0,
            method="Nelder-Mead",
            options={"maxfev": 150, "xatol": 1e-5, "fatol": abs(best_value) * 1e-4},
        )

    seed_indices = _select_seeds(geometry_points, values, spacing, max(max_beam_width, 1))
    for i in seed_indices:  # seed-local spacing; mixed-density (hybrid) grids can be coarser at the seed
        run_branch(points[i], float(values[i]), max(spacing, float(nearest[i])))

    if n_audit_points:  # post-convergence random audit; assumes nothing about landscape smoothness
        for n_reseeds in range(3):
            pre_audit_best = pooled_value
            audit_points = interp.sample(n_audit_points, rng)
            audit_values = run(audit_points)
            best_idx = int(np.argmax(audit_values))
            audit_best = float(audit_values[best_idx])
            if not np.isfinite(audit_best) or (
                np.isfinite(pre_audit_best)
                and audit_best - pre_audit_best <= tolerance * (abs(pre_audit_best) or abs(audit_best))
            ):
                break
            if n_reseeds >= 2:  # allow at most 2 audit->re-seed rounds
                warnings.warn(
                    "The `optimise` random audit is still finding significant improvements after 2 "
                    "re-seeding rounds, suggesting a challenging (sharply-featured) target landscape; the "
                    "returned optimum may not be the true global optimum. A finer "
                    "`initial_grid_resolution` and/or larger `n_audit_points` may help."
                )
                break
            run_branch(audit_points[best_idx], audit_best, spacing)

    assert pooled_point is not None  # every supported grid contains at least one point
    return _SearchResult(point=pooled_point, value=pooled_value)
