name: Build and test package

on:
  pull_request:
    branches:
       - master
       - develop
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

      matrix:
        python-version: ['3.8', '3.9']

    name: Python ${{ matrix.python-version }} Test Pop

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel
          pip install numpy
          pip install -e .
          pip install -e .[tests]

      - name: Test
        run:  |
          pytest tests/test_*.py
          pytest doped/pycdt/core/tests/test_*.py
