name: MacOS Tests

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed  # only test when new release has been deployed to PyPI

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        python-version: [ '3.11' ]
        os: [ macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Test
        run:  |
          pytest --mpl -vv --log-level=INFO tests  # test everything

      - name: Generate GH Actions test plots
        if: always()  # always generate the plots, even if the tests fail
        run:  |
          # Generate the test plots in case there were any failures:
          pytest --mpl-generate-path=tests/remote_baseline -k "plot" tests

      # Upload test plots
      - name: Archive test plots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: output-plots
          path: tests/remote_baseline
